<a href="https://colab.research.google.com/github/imadangada/covid-19-data-analysis-with-python/blob/main/imad.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import itertools
import pandas as pd
import numpy as np
import matplotlib.ticker as ticker
from sklearn import preprocessing
%matplotlib inline

In [ ]:
import os 
os.getcwd()

'/content'

In [ ]:
from google.colab import files
files.upload()

Saving who2.csv to who2.csv


{'who2.csv': b'\xef\xbb\xbfName,WHO Region,Cases - cumulative total,Cases - cumulative total per 100000 population,Cases - newly reported in last 7 days,Cases - newly reported in last 7 days per 100000 population,Cases - newly reported in last 24 hours,Deaths - cumulative total,Deaths - cumulative total per 100000 population,Deaths - newly reported in last 7 days,Deaths - newly reported in last 7 days per 100000 population,Deaths - newly reported in last 24 hours\r\nUnited States of America,Americas,35010407,10577.08,618994,187.01,78722,609022,183.99,2759,0.83,387\r\nBrazil,Americas,19953501,9387.26,245839,115.66,15143,557223,262.15,6721,3.16,389\r\nArgentina,Americas,4947030,10945.78,87860,194.4,11183,106045,234.63,1940,4.29,273\r\nColombia,Americas,4801050,9435.49,64701,127.16,6636,121216,238.23,2034,4,218\r\nMexico,Americas,2861498,2219.37,107060,83.04,6506,241279,187.14,2684,2.08,245\r\nPeru,Americas,2114445,6412.88,9440,28.63,1244,196518,596.02,545,1.65,80\r\nChile,Americas,161845

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv("who2.csv")

In [ ]:
data.head()

Name  ... Deaths - newly reported in last 24 hours
0  United States of America  ...                                      387
1                    Brazil  ...                                      389
2                 Argentina  ...                                      273
3                  Colombia  ...                                      218
4                    Mexico  ...                                      245

[5 rows x 12 columns]

In [ ]:
data.describe()

Cases - cumulative total  ...  Deaths - newly reported in last 24 hours
count              5.600000e+01  ...                                 56.000000
mean               1.387297e+06  ...                                 34.928571
std                5.364471e+06  ...                                 89.166006
min                7.000000e+00  ...                                  0.000000
25%                2.438750e+03  ...                                  0.000000
50%                2.071600e+04  ...                                  0.500000
75%                3.888312e+05  ...                                 11.250000
max                3.501041e+07  ...                                389.000000

[8 rows x 10 columns]

In [ ]:
data.head()

Name  ... Deaths - newly reported in last 24 hours
0  United States of America  ...                                      387
1                    Brazil  ...                                      389
2                 Argentina  ...                                      273
3                  Colombia  ...                                      218
4                    Mexico  ...                                      245

[5 rows x 12 columns]

In [ ]:
#Import libraries 
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LinearRegression 
%matplotlib inline

In [ ]:
X = data[['Cases - cumulative total']] 
Y = data['Deaths - cumulative total'] 
lm = LinearRegression() 
lm 
lm.fit(X,Y)
lm.score(X, Y)

0.879731556925817

In [ ]:
X = data[['Cases - cumulative total']] 
Y = data['Deaths - cumulative total'] 
lm = LinearRegression()
lm
lm.fit(X,Y)

Yhat=lm.predict(X)
Yhat[0:5]

array([715801.38585336, 411379.48842034, 107977.29041276, 105025.85347165,
        65811.81441143])

In [ ]:
lm.intercept_

7957.78711918573

In [ ]:
lm.coef_

array([0.02021809])

In [ ]:
X=data.drop(['Name','WHO Region','Deaths - cumulative total'], axis=1)

In [ ]:
lm.fit(X,Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
lm.intercept_

-1227.8920349813343

In [ ]:
lm.coef_

array([ 9.71886043e-03, -3.92296517e+00,  2.62316400e+00,  1.69894848e+01,
       -1.75746010e+01,  2.85531899e+02, -1.75580910e+01, -6.52335474e+02,
        1.65748526e+02])

In [ ]:
# fit the model 
lm.fit(X, data['Deaths - cumulative total'])
# Find the R^2
print('The R-square is: ', lm.score(X, data['Deaths - cumulative total']))

The R-square is:  0.9929765414145906


In [ ]:
from scipy import stats

In [ ]:
pearson_coef, p_value = stats.pearsonr(data['Deaths - cumulative total'], data['Cases - cumulative total'])
print("The Pearson Correlation Coefficient is", pearson_coef, " with a P-value of P =", p_value)

The Pearson Correlation Coefficient is 0.9379400604120807  with a P-value of P = 1.6772550130122968e-26
